name: zing_call
description: ZegoCloud Audio/Video Calling App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Yahan se '^' hata diya hai taaki exact stable version (4.1.9) hi use ho
  zego_uikit_prebuilt_call: 4.1.9

flutter:
  uses-material-design: true
