name: zing_call
description: ZegoCloud Audio/Video Calling App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  zego_uikit_prebuilt_call: 4.1.9

# 🔥 YEH HAI ASLI FIX JO KOTLIN ERROR KO JAD SE KHATAM KAREGA 🔥
dependency_overrides:
  is_lock_screen2: 2.0.2

flutter:
  uses-material-design: true
