name: zing_call
description: ZegoCloud Audio/Video Calling App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 'any' lagane se system sabse latest aur 100% compatible package uthayega, error wale nahi.
  zego_uikit_prebuilt_call: any

flutter:
  uses-material-design: true
